# Generated by Django 4.2.1 on 2023-05-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes_productos')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=1000)),
                ('tipo', models.CharField(max_length=64)),
                ('cant_nico', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('precio_min', models.IntegerField()),
                ('precio_may', models.IntegerField()),
                ('cant_min_may', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
