# Generated by Django 4.2.1 on 2023-05-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0003_producto_delete_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cant_nico',
            new_name='cant_nicotina',
        ),
    ]
